services:
  mytuner:
    build: .
    container_name: mytuner
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./data:/app/data
      - ./plugins:/app/plugins
    environment:
      - TZ=Europe/Berlin
